const data=[
		{
			"groupList":[
				{
					"groupList":[],
					"id":1657,
					"level":2,
					"name":"v",
					"parentId":1655,
					"title":"v"
				},
				{
					"groupList":[
						{
							"groupList":[],
							"id":1659,
							"level":3,
							"name":"ccc",
							"parentId":1658,
							"title":"ccc"
						},
						{
							"groupList":[],
							"id":1660,
							"level":3,
							"name":"dd",
							"parentId":1658,
							"title":"dd"
						},
						{
							"groupList":[],
							"id":1661,
							"level":3,
							"name":"ee",
							"parentId":1658,
							"title":"dd"
						}
					],
					"id":1658,
					"level":2,
					"name":"b",
					"parentId":1655,
					"title":"b"
				}
			],
			"id":1655,
			"level":1,
			"name":"木作",
			"parentId":0,
			"title":"木作"
		},
		{
			"groupList":[],
			"id":1646,
			"level":1,
			"name":"地砖",
			"parentId":0,
			"title":"地砖"
	},
	{
		"groupList":[],
		"id":1647,
		"level":1,
		"name":"墙纸",
		"parentId":0,
		"title":"墙纸"
	},
		
]
export default data